### PR TITLE
Build on Ubuntu without Docker for the sake of documentation

### PR DESCRIPTION
**Pull request by probonopd**
Everything in one yml file for ease of understanding. No Docker.

For https://github.com/AppImageCommunity/AppImageUpdate/issues/239

### CODE REVIEW

**Comment by probonopd** [comment]
Probably more shenanigans from https://github.com/AppImageCommunity/AppImageUpdate/blob/main/ci/Dockerfile.x86_64 are needed...

**Comment by TheAssassin** [comment]
This is pointless, redundant and ultimately unnecessary. I wouldn't want to maintain this. It wastes resources with a superfluous unsupported build job. It does not provide _any_ benefit for the community. See #239.

**Comment by probonopd** [comment]
Even if we end up [not](https://github.com/AppImage/appimagetool/releases/tag/continuou) merging this, I'd like to document how to build this without Docker. And I am (ab)using this PR to get builds done in a documented way (as opposed to a local dev machine).

**Comment by probonopd** [comment]
This has now served its intended purpose; the results are in
* https://github.com/AppImageCommunity/AppImageUpdate/pull/242

**Pull request closed without merging**
